### ISSUE TITLE
TypeError when applying toobar filter on grid with PhpArray datasource and null value in data

### ISSUE THREAD

**Issue by olexp** [zfc-datagrid/zfc-datagrid#88]
Error:
```
TypeError: ZfcDatagrid\Column\Type\AbstractType::getFilterValue(): Argument #1 ($val) must be of type string, null given, called in C:\work\php\laminas\vendor\zfc-datagrid\zfc-datagrid\src\ZfcDatagrid\DataSource\PhpArray\Filter.php on line 48 and defined in C:\work\php\laminas\vendor\zfc-datagrid\zfc-datagrid\src\ZfcDatagrid\Column\Type\AbstractType.php:50
Stack trace:
#0 C:\work\php\laminas\vendor\zfc-datagrid\zfc-datagrid\src\ZfcDatagrid\DataSource\PhpArray\Filter.php(48): ZfcDatagrid\Column\Type\AbstractType->getFilterValue(NULL)
#1 [internal function]: ZfcDatagrid\DataSource\PhpArray\Filter->applyFilter(Array)
#2 C:\work\php\laminas\vendor\zfc-datagrid\zfc-datagrid\src\ZfcDatagrid\DataSource\PhpArray.php(62): array_filter(Array, Array)
#3 C:\work\php\laminas\vendor\zfc-datagrid\zfc-datagrid\src\ZfcDatagrid\Datagrid.php(1018): ZfcDatagrid\DataSource\PhpArray->execute()
#4 C:\work\php\laminas\vendor\zfc-datagrid\zfc-datagrid\src\ZfcDatagrid\Datagrid.php(1100): ZfcDatagrid\Datagrid->loadData()
#5 C:\work\php\laminas\vendor\zfc-datagrid\zfc-datagrid\src\ZfcDatagrid\Datagrid.php(1240): ZfcDatagrid\Datagrid->render()
```

Also, this method works correctly now for non-string types like int it will stop working when strict types declaration will be added to the class file.
Possible solution could be to cast value to string before calling method in ZfcDatagrid\DataSource\PhpArray::applyFilter()

```php
            $value = (string) $row[$col->getUniqueId()];
            $value = $col->getType()->getFilterValue($value);
```

PHP: 8.0.3
zfc-datagrid/zfc-datagrid: 2.0.0

To reproduce:
```php
        $grid = $this->serviceLocator->get('ZfcDatagrid\Datagrid');
        $grid->addColumn(new Column\Select('name'));
        $grid->addColumn(new Column\Select('value'));
        $grid->setDataSource([
            ['name' => 'name', 'value' => null],
        ]);
        $grid->getResponse();
```

**Comment by kokspflanze** [comment]
Did you added the `strict types` into the class file in your vendor version?

personal it looks bit like, a bigger change to update all files to the strict mode.

**Comment by olexp** [comment]
I did not. With such prototype ZfcDatagrid\Column\Type\AbstractType:getFilterValue method will fail even without strict types:
```php
    public function getFilterValue(string $val): string
    {
        return $val;
    }
```
